language: generic 
udo: required
services:
  - docker

before_install:
  - docker build -t attreyakapil/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true attreyakapil/docker-react npm run test