language: generic 
udo: required
services:
  - docker

before_install:
  - docker build -t attreyakapil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true attreyakapil/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-277616157653"
  bucket_path: "docker-react"
  on:
    brnach: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

